### ISSUE TITLE
Vault can't be migrated

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/canutin#155]
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "Canutin.dev.vault" at "file:../Canutin.dev.vault"

Error: Migration engine exited.
Error: command failed with exit code 1
    at runPrismaMigrate (file:///home/srg/canutin/server/chunks/prisma-a4d71516.js:58:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateVaultMigration (file:///home/srg/canutin/server/chunks/prisma-a4d71516.js:71:3)
    at async load (file:///home/srg/canutin/server/chunks/20-1f136ca9.js:9:22)
    at async load_server_data (file:///home/srg/canutin/server/index.js:1547:18)
    at async file:///home/srg/canutin/server/index.js:2430:18
Error: command failed with exit code 1
    at runPrismaMigrate (file:///home/srg/canutin/server/chunks/prisma-a4d71516.js:58:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async validateVaultMigration (file:///home/srg/canutin/server/chunks/prisma-a4d71516.js:71:3)
    at async load (file:///home/srg/canutin/server/chunks/20-1f136ca9.js:9:22)
    at async load_server_data (file:///home/srg/canutin/server/index.js:1547:18)
    at async file:///home/srg/canutin/server/index.js:2430:18
```

**Comment by fmaclen** [comment]
This was a permission issue, fixed it by:
- `chmod 755 ./node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x`
